"""Build release archives and a Homebrew formula using only the Python standard library."""
import argparse
import gzip
import hashlib
import io
import json
import os
from pathlib import Path
import platform
import re
import shutil
import subprocess
import tarfile
import tempfile
import zipfile

ROOT = Path(__file__).resolve().parent.parent
TARGETS = ('macos-arm64', 'macos-x64', 'linux-arm64', 'linux-x64', 'windows-x64')
REPOSITORY = 'mcquenji/tug'
SEMVER = r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'


def version():
    match = re.search(r'^version:\s*[\'"]?(' + SEMVER + r')[\'"]?\s*$', (ROOT / 'pubspec.yaml').read_text(), re.M)
    if not match:
        raise ValueError('pubspec.yaml must contain a stable major.minor.patch version')
    return match[1]


def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT, text=True).strip()


def validate_tag(tag):
    if not re.fullmatch('v' + SEMVER, tag) or tag != f'v{version()}':
        raise ValueError('Release tag must equal v<pubspec.yaml version>, with no prerelease or build suffix')
    commit = git('rev-parse', 'HEAD')
    if git('rev-parse', f'refs/tags/{tag}^{{commit}}') != commit:
        raise ValueError('Checkout does not match the release tag')
    return {'version': version(), 'tag': tag, 'commit': commit}


def filename(release_version, target):
    if target not in TARGETS:
        raise ValueError(f'Unsupported release target: {target}')
    suffix = 'zip' if target.startswith('windows-') else 'tar.gz'
    return f'tug-v{release_version}-{target}.{suffix}'


def package(target, output):
    actual_os = {'Darwin': 'macos', 'Linux': 'linux', 'Windows': 'windows'}[platform.system()]
    actual_arch = {'aarch64': 'arm64', 'arm64': 'arm64', 'amd64': 'x64', 'x86_64': 'x64'}[platform.machine().lower()]
    if target != f'{actual_os}-{actual_arch}':
        raise ValueError('Release target must match the native build host')
    binary_name = 'tug.exe' if actual_os == 'windows' else 'tug'
    binary = ROOT / 'build' / binary_name
    release_version = version()
    # Exercise the executable without source files or user configuration nearby.
    with tempfile.TemporaryDirectory(prefix='tug-release-') as empty:
        isolated = Path(empty) / binary_name
        shutil.copy2(binary, isolated)
        environment = {**os.environ, 'TUG_GLOBAL_DIR': empty, 'TUG_LOCAL_DIR': empty, 'NO_COLOR': '1'}
        result = subprocess.run([str(isolated), '--version'], cwd=empty, env=environment, check=True, capture_output=True, text=True)
        if result.stdout.strip() != f'tug {release_version}':
            raise ValueError('Compiled executable version does not match pubspec.yaml')
        subprocess.run([str(isolated), '--help'], cwd=empty, env=environment, check=True, stdout=subprocess.DEVNULL)
    metadata = {'version': release_version, 'commit': git('rev-parse', 'HEAD'), 'target': target}
    files = {
        binary_name: binary.read_bytes(),
        'README.md': (ROOT / 'README.md').read_bytes(),
        'release.json': (json.dumps(metadata, indent=2) + '\n').encode(),
    }
    output.mkdir(parents=True, exist_ok=True)
    archive_path = output / filename(release_version, target)
    if actual_os == 'windows':
        with zipfile.ZipFile(archive_path, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
            for name, data in files.items():
                info = zipfile.ZipInfo(name, (1980, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(info, data)
    else:
        with archive_path.open('wb') as raw, gzip.GzipFile(fileobj=raw, filename='', mode='wb', mtime=0) as compressed, tarfile.open(fileobj=compressed, mode='w') as archive:
            for name, data in files.items():
                info = tarfile.TarInfo(name)
                info.size = len(data)
                info.mode = 0o755 if name == binary_name else 0o644
                archive.addfile(info, io.BytesIO(data))
    print(f'Packaged and smoke-tested {archive_path}')


def archive_metadata(path):
    if path.suffix == '.zip':
        with zipfile.ZipFile(path) as archive:
            return json.loads(archive.read('release.json'))
    with tarfile.open(path, 'r:gz') as archive:
        return json.load(archive.extractfile('release.json'))


def formula(release_version, checksums):
    def resource(target, indent):
        return '\n'.join(' ' * indent + line for line in [
            f'url "https://github.com/{REPOSITORY}/releases/download/v{release_version}/{filename(release_version, target)}"',
            f'sha256 "{checksums[target]}"',
        ])
    return f'''# Generated by Tug's tagged-release workflow. Do not edit by hand.
class Tug < Formula
  desc "Deploy Serverpod applications to Coolify"
  homepage "https://github.com/{REPOSITORY}"
  version "{release_version}"

  depends_on "fvm"
  depends_on "git"

  on_macos do
    depends_on macos: :sequoia
    on_arm do
{resource('macos-arm64', 6)}
    end
    on_intel do
{resource('macos-x64', 6)}
    end
  end

  on_linux do
    on_arm do
{resource('linux-arm64', 6)}
    end
    on_intel do
{resource('linux-x64', 6)}
    end
  end

  def install
    bin.install "tug"
  end

  test do
    assert_equal "tug #{{version}}", shell_output("#{{bin}}/tug --version").strip
  end
end
'''


def prepare(directory, tag):
    release = validate_tag(tag)
    checksums = {}
    lines = []
    for target in TARGETS:
        archive = directory / filename(release['version'], target)
        if archive_metadata(archive) != {**{k: release[k] for k in ('version', 'commit')}, 'target': target}:
            raise ValueError(f'{archive.name}: release metadata mismatch')
        checksums[target] = hashlib.sha256(archive.read_bytes()).hexdigest()
        lines.append(f'{checksums[target]}  {archive.name}\n')
    (directory / 'SHA256SUMS').write_text(''.join(lines))
    (directory / 'tug.rb').write_text(formula(release['version'], checksums))
    print('Verified all five native archives and generated Homebrew formula')


def publish(directory, tag):
    release = validate_tag(tag)
    # Never overwrite an already-published release. Failed draft uploads can resume.
    existing = subprocess.run(['gh', 'release', 'view', tag, '--repo', REPOSITORY, '--json', 'isDraft'], capture_output=True, text=True)
    if existing.returncode == 0:
        if not json.loads(existing.stdout)['isDraft']:
            raise ValueError('Release is already published. Retry only the failed tap job, or publish a new version.')
    else:
        subprocess.run(['gh', 'release', 'create', tag, '--repo', REPOSITORY, '--verify-tag', '--draft', '--title', f'Tug {release["version"]}', '--generate-notes'], check=True)
    assets = [str(directory / filename(release['version'], t)) for t in TARGETS]
    subprocess.run(['gh', 'release', 'upload', tag, '--repo', REPOSITORY, '--clobber', *assets, str(directory / 'SHA256SUMS')], check=True)
    subprocess.run(['gh', 'release', 'edit', tag, '--repo', REPOSITORY, '--draft=false'], check=True)


def update_tap(source, destination):
    new_text = source.read_text()
    def formula_version(text):
        match = re.search(r'^  version "(' + SEMVER + r')"$', text, re.M)
        if not match:
            raise ValueError('Invalid formula version')
        return tuple(map(int, match[1].split('.')))
    new = formula_version(new_text)
    if destination.exists() and formula_version(destination.read_text()) > new:
        print('A newer release is already in the tap; leaving it unchanged')
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(new_text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest='command', required=True)
    metadata = commands.add_parser('metadata')
    metadata.add_argument('--tag', required=True)
    bundle = commands.add_parser('package')
    bundle.add_argument('--target', required=True, choices=TARGETS)
    bundle.add_argument('--output', type=Path, default=ROOT / 'dist')
    for name in ('prepare', 'publish'):
        command = commands.add_parser(name)
        command.add_argument('--tag', required=True)
        command.add_argument('--directory', type=Path, default=ROOT / 'dist')
    tap = commands.add_parser('update-tap')
    tap.add_argument('--source', type=Path, required=True)
    tap.add_argument('--destination', type=Path, required=True)
    args = parser.parse_args()
    if args.command == 'metadata':
        values = validate_tag(args.tag)
        with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as output:
            for key, value in values.items():
                output.write(f'{key}={value}\n')
    elif args.command == 'package':
        package(args.target, args.output)
    elif args.command == 'prepare':
        prepare(args.directory, args.tag)
    elif args.command == 'publish':
        publish(args.directory, args.tag)
    elif args.command == 'update-tap':
        update_tap(args.source, args.destination)


if __name__ == '__main__':
    main()
